export const profile = {
  name: "Siu Ming Ngai Owen",
  shortName: "Owen Siu",
  email: "owensiu1002@gmail.com",
  github: "https://github.com/owen1002",
  linkedin: "https://linkedin.com/in/ming-ngai-owen-siu-a26012133",
  medium:"https://medium.com/@owensiu",
  mobile: "+852 68434007",
};

export const education = {
  university: "HKUST",
  major: "Computer Engineering",
  graduatedAt: new Date(2016, 11, 17),
};

export const workingExp = [
  {
    company: "Morgan Stanley",
    location: "Hong Kong",
    position: "Prime Brokerage Tooling Strategist",
    period: "Mar 2022 to present",
    remark: "Agency Contract from Robert Walters Hong Kong Limited",
    techStack: [
      "TypeScript",
      "React",
      "Redux",
      "Ant Design",
      "Tailwind CSS",
      ".NET Core",
      "MongoDB",
      "kdb+ q",
    ],
    projects: [
      "Designed UI/UX and built web client and services for client account management and swap simulation system",
      "Performed reverse engineering on legacy systems",
    ],
  },
  {
    company: "CLSA",
    location: "Hong Kong",
    position: "Software Engineer",
    period: "Oct 2021 - Feb 2022",
    remark: "",
    techStack: ["Typescript", "React", "Next.js", "MaterialUI", "Docker"],
    projects: ["Built web client for client management system"],
  },
  {
    company: "FWD Life Insurance Company (Bermuda) Limited",
    location: "Hong Kong",
    position: "System Analyst",
    period: "Jan 2021 - Sep 2021",
    remark: "Agency Contract from Cornerstone Global Partners",
    techStack: [
      "Typescript",
      "React",
      "Next.js",
      "NestJS",
      "MaterialUI",
      "MongoDB",
      "GraphQL",
      "Microservices",
      "AWS",
      "Docker",
    ],
    projects: [
      "Developed 13 microservices from scratch for e-commerce platform and merge query/mutation into one endpoint for web client through GraphQL Federation",
      "Lead a team of 2 engineers to launch CMS cache system built with MongoDB Atlas",
      "Collaborate with team leads and scrum master to perform an agile development process.",
    ],
  },
  {
    company: "AVA Intelligent Partners Limited",
    location: "Hong Kong",
    position: "Senior Programmer",
    period: "Jun 2018 - Dec 2020",
    remark: "",
    techStack: [
      "Typescript",
      "React",
      "MaterialUI",
      "Node.js",
      ".NET Core",
      "PostgreSQL",
      "MongoDB",
      "GraphQL",
      "Docker",
    ],
    projects: [
      "Developed web client and services from scratch for Internal ERP system",
      "Developed web client and services from scratch for ESG report generation system",
      "Research and analyze on SEO to boost the ranking of firm's official website",
    ],
  },
  {
    company: "Lucky Technology Ltd.",
    location: "Hong Kong",
    position: "Programmer",
    period: "Aug 2016 - May 2018",
    remark: "",
    techStack: ["JavaScript", "AngularJS", "Node.js", ".NET Core", "SQL"],
    projects: [
      "Built web client and services from scratch and worked with hardware engineers to bootstrap time and attendance system",
    ],
  },
];
